# .github/labeler.yml - Automatic labeling based on changed files

frontend:
  - 'public/**'
  - 'js/**'
  - '*.html'
  - 'css/**'

backend:
  - 'routes/**'
  - 'models/**'
  - 'server.js'
  - 'scripts/**'

database:
  - 'models/**'
  - 'scripts/seed.js'

docker:
  - 'Dockerfile'
  - 'docker-compose.yml'
  - '.dockerignore'

tests:
  - 'tests/**'
  - '**/*.test.js'

ci-cd:
  - '.github/workflows/**'

documentation:
  - '*.md'
  - 'docs/**'

dependencies:
  - 'package.json'
  - 'package-lock.json'

configuration:
  - '.env*'
  - '.eslintrc*'
  - '.prettierrc*'
